[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "https://following-claude-charlesxstorm-c20ba5bb.koyeb.app/:splat"
status = 200

[build]
  base = "client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  VITE_API_URL = "/api/v1/conflix/users"
  VITE_PROXY_URL = "/api/"
